site_name: Belajarpython – Situs Open Source Tutorial Pemrograman Python Bahasa Indonesia
site_author: Purwanto
theme:
    name: null
    custom_dir: 'belajarpython_theme/' 
plugins:
    - meta-descriptions:
        export_csv: false
        quiet: false
        enable_checks: false
        min_length: 50
        max_length: 160
# plugins:
#     - categories

    # static_templates:
    #     - 404.html

    # locale: en

    # include_search_page: false
    # search_index_only: false

    # highlightjs: true
    # hljs_languages: []
    # hljs_style: github

    # navigation_depth: 2
    # nav_style: primary

    # analytics:
    # gtag: null

    # shortcuts:
    #     help: 191    # ?
    #     next: 78     # n
    #     previous: 80 # p
    #     search: 83   # s
